name: Build and Deploy

on:
  pull_request:
    branches:
      - master
    types: [closed]
    
jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
          

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: yarn install
        run: yarn install

      - name: Clean public
        run: rm -rf ./public/*

      - name: Clean docs
        run: rm -rf ./docs/*

      - name: Build
        run: gatsby build --prefix-paths
      
      - name: Check build result/
        run: ls -la public

      - name: Upload docs
        run: mv public/* docs/ 

      - name: Check upload result
        run: ls -la docs


      - name: git setting
        run: |
          git config --local user.email "${{ secrets.GH_email }}"
          git config --local user.name "${{ secrets.GH_name }}"
          
          
      - name: Commit files
        run: |
          git add .
          git commit -m "Update pages"
          git pull
          git push origin master

